# Generated by Django 5.0.1 on 2024-04-08 20:31

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_image_alter_profile_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='deafult.png', upload_to=user.models.get_upload_path),
        ),
    ]
